In [ ]:
import numpy as np

In [ ]:
a = np.zeros(5) #Return a new array of given shape and type, filled with zeros.

In [ ]:
a

array([0., 0., 0., 0., 0.])

In [ ]:
a.ndim

1

In [ ]:
b = np.zeros((3, 4))

In [ ]:
b.ndim

2

In [ ]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.twos(5) #doesnt exist in numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
np.array([[2, 2, 2], [2, 2, 2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [ ]:
arr = np.zeros((3, 4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr.ndim

2

In [ ]:
#3 dimensional array
np.zeros(1)

array([0.])

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.zeros((3, 4))
arr.ndim

2

In [ ]:
arr = np.zeros((1, 3, 4))
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr.ndim

3

In [ ]:
arr = np.zeros((1, 1, 3, 4))
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [ ]:
arr.ndim

4

In [ ]:
arr = np.zeros((1, 1, 1, 3, 4))
arr

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [ ]:
arr.ndim

5

In [ ]:
arr

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [ ]:
arr = np.ones((3, 4))

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
a = arr * 5

In [ ]:
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
a - 1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [ ]:
np.eye(3) #Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.empty((3, 4)) #Return a new array of given shape and type, without initializing entries

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [ ]:
#optional >> random module

import random
random.choice((1, 2, 3, 4, 5))

2

In [ ]:
random.choice('Ajay')

'a'

In [ ]:
random.randrange(1, 10)

7

In [ ]:
random.random() # a random no is generated between 0(included) and 1 (excluded)

0.017769477320319083

In [ ]:
lis = [1, 2, 3, 4, 5]
lis

[1, 2, 3, 4, 5]

In [ ]:
random.shuffle(lis)

In [ ]:
lis

[2, 3, 1, 4, 5]

In [ ]:
random.uniform(7, 14)

12.573243031183921

In [ ]:

#random numbers related concepts in numpy
np.array([])

array([], dtype=float64)

In [ ]:
np.random.random_sample()

0.4880220291522446

In [ ]:
np.random.random_sample((5, ))

array([0.03546162, 0.96439444, 0.86559857, 0.45990473, 0.68239288])

In [ ]:
np.random.rand(1)

array([0.89826893])

In [ ]:
np.random.rand(2, 3)

array([[0.19956744, 0.85663567, 0.76798966],
       [0.01678481, 0.29287439, 0.5507118 ]])

In [ ]:
np.random.randn(2,3)

array([[-0.85502332, -0.06881989,  0.76879661],
       [ 0.64187717,  1.46547139, -1.07173591]])

In [ ]:
arr = np.random.randint(1, 5, size= (3, 4))

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.size

12

In [ ]:
arr

array([[1, 3, 3, 4],
       [4, 3, 3, 3],
       [4, 4, 1, 4]])

In [ ]:
#reshaping the array

arr1 = arr.reshape(2, 6)

In [ ]:
arr1.shape

(2, 6)

In [ ]:
arr1.size

12

In [ ]:
arr

array([[1, 3, 3, 4],
       [4, 3, 3, 3],
       [4, 4, 1, 4]])

In [ ]:
arr.size

12

In [ ]:
#array size will not change, always resape parameter should be multiplication of original array size

In [ ]:
arr

array([[1, 3, 3, 4],
       [4, 3, 3, 3],
       [4, 4, 1, 4]])

In [ ]:
arr.size

12

In [ ]:
arr.reshape(12,1)

array([[1],
       [3],
       [3],
       [4],
       [4],
       [3],
       [3],
       [3],
       [4],
       [4],
       [1],
       [4]])

In [ ]:
arr.reshape(1, 12)

array([[1, 3, 3, 4, 4, 3, 3, 3, 4, 4, 1, 4]])

In [ ]:
arr.reshape(3, 3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [ ]:
arr.reshape(3,4)

array([[1, 3, 3, 4],
       [4, 3, 3, 3],
       [4, 4, 1, 4]])

In [ ]:
#case when you dont know in reshape what should be the column count

arr.reshape(4, -1)

array([[1, 3, 3],
       [4, 4, 3],
       [3, 3, 4],
       [4, 1, 4]])

In [ ]:
arr.reshape(2, -1)

array([[1, 3, 3, 4, 4, 3],
       [3, 3, 4, 4, 1, 4]])

In [ ]:
arr.reshape(2, -100)

array([[1, 3, 3, 4, 4, 3],
       [3, 3, 4, 4, 1, 4]])

In [ ]:
arr1 = arr.reshape(-1, 3)#you know column count but no row count

In [ ]:
arr1.size

12

In [ ]:
arr.reshape(12, 1)

array([[1],
       [3],
       [3],
       [4],
       [4],
       [3],
       [3],
       [3],
       [4],
       [4],
       [1],
       [4]])

In [ ]:
arr.reshape(12, 1).base #to see the original array

array([[1, 3, 3, 4],
       [4, 3, 3, 3],
       [4, 4, 1, 4]])

In [ ]:
arr.reshape(2, 2, 3)

array([[[1, 3, 3],
        [4, 4, 3]],

       [[3, 3, 4],
        [4, 1, 4]]])

In [ ]:
arr.reshape(1, 2, 2, 3)

array([[[[1, 3, 3],
         [4, 4, 3]],

        [[3, 3, 4],
         [4, 1, 4]]]])

In [ ]:
arr.reshape(1, 2, 2, 3).ndim

4

In [ ]:
arr.reshape(4, 3, 1) #3 rows 1 column repeated 4 times in the third dimension

array([[[1],
        [3],
        [3]],

       [[4],
        [4],
        [3]],

       [[3],
        [3],
        [4]],

       [[4],
        [1],
        [4]]])

In [ ]:
#conditions on array

arr1 = np.random.randint(1, 10, (5,6))

In [ ]:
arr1

array([[3, 8, 8, 1, 1, 7],
       [4, 4, 5, 5, 2, 5],
       [2, 2, 9, 9, 2, 4],
       [8, 5, 4, 1, 4, 9],
       [7, 8, 4, 9, 6, 9]])

In [ ]:
arr1.shape

(5, 6)

In [ ]:
arr1.ndim

2

In [ ]:
arr1.size

30

In [ ]:
arr1 > 3

array([[False,  True,  True, False, False,  True],
       [ True,  True,  True,  True, False,  True],
       [False, False,  True,  True, False,  True],
       [ True,  True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [ ]:
arr1[arr1> 3]

array([8, 8, 7, 4, 4, 5, 5, 5, 9, 9, 4, 8, 5, 4, 4, 9, 7, 8, 4, 9, 6, 9])

In [ ]:
arr1[arr1 < 3]

array([1, 1, 2, 2, 2, 2, 1])

In [ ]:
arr1

array([[3, 8, 8, 1, 1, 7],
       [4, 4, 5, 5, 2, 5],
       [2, 2, 9, 9, 2, 4],
       [8, 5, 4, 1, 4, 9],
       [7, 8, 4, 9, 6, 9]])

In [ ]:
#To access elements in the array
arr1[0]

array([3, 8, 8, 1, 1, 7])

In [ ]:
arr1[1]

array([4, 4, 5, 5, 2, 5])

In [ ]:
arr1[1][0]

4

In [ ]:
arr1

array([[3, 8, 8, 1, 1, 7],
       [4, 4, 5, 5, 2, 5],
       [2, 2, 9, 9, 2, 4],
       [8, 5, 4, 1, 4, 9],
       [7, 8, 4, 9, 6, 9]])

In [ ]:
arr1[0:3] #oth row, 1st row and 2nd row

array([[3, 8, 8, 1, 1, 7],
       [4, 4, 5, 5, 2, 5],
       [2, 2, 9, 9, 2, 4]])

In [ ]:
arr1[0:3, [0, 2]] #0to2nd row and 0th and 2nd column

array([[3, 8],
       [4, 5],
       [2, 9]])

In [ ]:
#slicing on both rows and column

In [ ]:
arr1

array([[3, 8, 8, 1, 1, 7],
       [4, 4, 5, 5, 2, 5],
       [2, 2, 9, 9, 2, 4],
       [8, 5, 4, 1, 4, 9],
       [7, 8, 4, 9, 6, 9]])

In [ ]:
arr1[0:3, 1:3]

array([[8, 8],
       [4, 5],
       [2, 9]])

In [ ]:
arr1[0:2, [0,1]]

array([[3, 8],
       [4, 4]])

In [ ]:
arr1[0, [1, 3]]

array([8, 1])

In [ ]:
arr1[2:4, [0, 3]]

array([[2, 9],
       [8, 1]])

In [ ]:
arr1[2:5]

array([[2, 2, 9, 9, 2, 4],
       [8, 5, 4, 1, 4, 9],
       [7, 8, 4, 9, 6, 9]])

In [ ]:
arr1[2:5, 0:2]

array([[2, 2],
       [8, 5],
       [7, 8]])

In [ ]:
#mathematical operation on two arrays
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [ ]:
arr1

array([[1, 2, 1],
       [2, 1, 1],
       [2, 1, 1]])

In [ ]:
arr2

array([[2, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [ ]:
arr1+arr2 #indewise elment addition

array([[3, 3, 2],
       [3, 3, 2],
       [3, 2, 3]])

In [ ]:
arr1-arr2 #indexwise element substraction

array([[-1,  1,  0],
       [ 1, -1,  0],
       [ 1,  0, -1]])

In [ ]:
arr1 * arr2 #index wise multiplication

array([[2, 2, 1],
       [2, 2, 1],
       [2, 1, 2]])

In [ ]:
arr1, arr2

(array([[1, 2, 1],
        [2, 1, 1],
        [2, 1, 1]]),
 array([[2, 1, 1],
        [1, 2, 1],
        [1, 1, 2]]))

In [ ]:
arr1 / arr2 #index wise divison

array([[0.5, 2. , 1. ],
       [2. , 0.5, 1. ],
       [2. , 1. , 0.5]])

In [ ]:
4/0

ZeroDivisionError: division by zero

In [ ]:
arr1 / 0 #in python zero divion error will come, but in numpy no error

/tmp/ipykernel_3900/824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
#matric multiplication>> different from index wise multiplication

arr1 @ arr2 #1st way to do matrix multiplication

array([[5, 6, 5],
       [6, 5, 5],
       [6, 5, 5]])

In [ ]:
np.dot(arr1, arr2) #ndst way to do matrix multiplication

array([[5, 6, 5],
       [6, 5, 5],
       [6, 5, 5]])

In [ ]:
arr = np.zeros((3, 4))

In [ ]:
#broadcasting
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.ndim

1

In [ ]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
a = np.array([[1, 2, 3, 4]])

In [ ]:
a

array([[1, 2, 3, 4]])

In [ ]:
#Transpose
a.T

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
arr1

array([[1, 2, 1],
       [2, 1, 1],
       [2, 1, 1]])

In [ ]:
arr1.T

array([[1, 2, 2],
       [2, 1, 1],
       [1, 1, 1]])