In [1]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [3]:
import numpy as np

arr = np.array([0,1,2,3,4,5])
print(arr.dtype)

int64


In [2]:
#2. Given a NumPy array 'arr', check if its data type is float64.

In [3]:
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)

float64


In [ ]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [6]:
arr = np.array([1+2j, 3-4j, 5+6j], dtype=np.complex128)

print(arr)


[1.+2.j 3.-4.j 5.+6.j]


In [7]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [12]:
a = [10 , 20 , 30]

arr = np.array(a)
print(arr.astype(float))

[10. 20. 30.]


In [13]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [14]:
r = np.array([1.23456789, 2.3456789, 3.456789, 4.56789])

arr_float32 = arr.astype(np.float32)
print(arr_float32.dtype)

float32


In [ ]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [17]:
def array_attributes(arr):
    
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    
    return shape,size,dtype

arr =  np.array([[1,2,3,4,5],[6,7,8,9,10]])

attributes = array_attributes(arr)
print("Shape:", attributes[0])
print("Size:", attributes[1])
print("Data type:", attributes[2])

Shape: (2, 5)
Size: 10
Data type: int64


In [1]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [4]:
def array_dimension(arr):
    return arr.ndim

ex_array = np.array([[10,20,30],[40,50,60]])
print(array_dimension(ex_array))

2


In [5]:
#8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [6]:
import numpy as np

def item_size_info(arr):
    item_size = arr.itemsize  # Size of each element in bytes
    total_size = arr.nbytes   # Total size in bytes
    return item_size, total_size

# Example usage:
# Create a NumPy array
example_array = np.array([[1, 2, 3], [4, 5, 6]])
item_size, total_size = item_size_info(example_array)
print(f"Item size: {item_size} bytes")
print(f"Total size: {total_size} bytes")

Item size: 8 bytes
Total size: 48 bytes


In [7]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [8]:
import numpy as np

def array_strides(arr):
    return arr.strides

# Example usage:
# Create a NumPy array
example_array = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(example_array)
print(f"Strides: {strides}")


Strides: (24, 8)


In [9]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [10]:
import numpy as np

def shape_stride_relationship(arr):
    shape = arr.shape   # Shape of the array
    strides = arr.strides  # Strides of the array
    return shape, strides

# Example usage:
# Create a NumPy array
example_array = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(example_array)
print(f"Shape: {shape}")
print(f"Strides: {strides}")


Shape: (2, 3)
Strides: (24, 8)


In [11]:
#11. Create a function 'create_zeros_array that takes an integer'n' as input and returns a NumPy array ofv zeros with 'n' elements.

In [13]:
import numpy as np

def create_zeros_array(n):
    return np.zeros(n)

# Example usage:
# Create a NumPy array of zeros with 5 elements
zeros_array = create_zeros_array(5)
print(zeros_array)  # Output: [0. 0. 0. 0. 0.]


[0. 0. 0. 0. 0.]


In [14]:
#12. Write a function 'create_ones_matrix' that takes integers 'rows' and 'cols' as inputs and generates a 2 NumPy array filled with ones of size 'rows x cols'.

In [1]:
import numpy as np

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

# Example usage
matrix = create_ones_matrix(3, 4)
print(matrix)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [2]:
#13. Write a function `generate_range_array' that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from 'start', ending at stop (exclusive), and with the specified `step'.

In [3]:
import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

# Example usage
range_array = generate_range_array(1, 10, 2)
print(range_array)

[1 3 5 7 9]


In [4]:
#14. Design a function 'generate_linear_space' that takes two floats 'start', 'stop', and an integer 'num' as arguments and generates a NumPy array with num equally spaced values between 'start' and 'stop' (inclusive).

In [5]:
def generate_linear_space(start, stop, num):
     return np.linspace(start, stop, num)
    
# Example usage
linear_space_array = generate_linear_space(0.0, 1.0, 5)
print(linear_space_array)



[0.   0.25 0.5  0.75 1.  ]


In [6]:
#15. Create a function 'create_identity_matrix' that takes an integer 'n' as input and generates a square identity matrix of size 'n x n` using 'numpy.eye'.

In [7]:
def create_identity_matrix(n):
    return np.eye(n)

# Example usage
identity_matrix = create_identity_matrix(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
#16. Write a function that takes a Python list and converts it into a NumPy array.

In [9]:
def convert_to_numpy_array(py_list):
    return np.array(py_list)

# Example usage
my_list = [1, 2, 3, 4, 5]
numpy_array = convert_to_numpy_array(my_list)
print(numpy_array)


[1 2 3 4 5]


In [10]:
#17. Create a NumPy array and demonstrate the use of 'numpy.view' to create a new array object with the same data.

In [11]:
import numpy as np

# Creating a NumPy array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Using numpy.view to create a new array with the same data
view_array = original_array.view()

# Modifying the view array will also modify the original array
view_array[0, 0] = 100

# Displaying both arrays
print("Original Array:")
print(original_array)
print("\nView Array:")
print(view_array)


Original Array:
[[100   2   3]
 [  4   5   6]]

View Array:
[[100   2   3]
 [  4   5   6]]


In [12]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [13]:


def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenating along the first axis (rows)
result_axis0 = concatenate_arrays(array1, array2)
print("Concatenated along axis 0:")
print(result_axis0)

# Concatenating along the second axis (columns)
result_axis1 = concatenate_arrays(array1, array2, axis=1)
print("\nConcatenated along axis 1:")
print(result_axis1)



Concatenated along axis 0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Concatenated along axis 1:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [14]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using 'numpy concatenate'.

In [15]:
import numpy as np

# Creating two NumPy arrays with different shapes
array1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
array2 = np.array([[7, 8], [9, 10]])       # Shape: (2, 2)

# Concatenating them horizontally
result = np.concatenate((array1, array2), axis=1)

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nConcatenated horizontally:")
print(result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8]
 [ 9 10]]

Concatenated horizontally:
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [16]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [17]:
def stack_arrays_vertically(arrays):
    return np.vstack(arrays)

# Example usage
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
array3 = np.array([[13, 14, 15], [16, 17, 18]])

# Stack arrays vertically
result = stack_arrays_vertically([array1, array2, array3])
print("Stacked vertically:")
print(result)


Stacked vertically:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [18]:
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [19]:
import numpy as np

def create_integer_array(start, stop, step):
    return np.arange(start, stop+1, step, dtype=int)

# Example usage:
start = 0
stop = 10
step = 2
result_array = create_integer_array(start, stop, step)
print(result_array)


[ 0  2  4  6  8 10]


In [20]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1(inclusive).

In [21]:
import numpy as np

def generate_equally_spaced_values():
    return np.linspace(0, 1, 10)

# Example usage:
result_array = generate_equally_spaced_values()
print(result_array)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [22]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [23]:
import numpy as np

def generate_logarithmically_spaced_values():
    return np.logspace(0, 3, 5)

# Example usage:
result_array = generate_logarithmically_spaced_values()
print(result_array)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [25]:
#24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100. 


In [27]:
 #code  
    
    
import numpy as np
import pandas as pd

# Create a NumPy array of random integers
random_array = np.random.randint(1, 101, size=(5, 3))

# Create a DataFrame from the NumPy array
df = pd.DataFrame(random_array, columns=['Column 1', 'Column 2', 'Column 3'])

print(df)

   Column 1  Column 2  Column 3
0        41        98       100
1        70        26        94
2        43        40        85
3        80        28        83
4        87        28        24


In [28]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [29]:
def replace_negative_with_zeros(dataframe, column_name):
    # Replace negative values with zeros using NumPy where function
    dataframe[column_name] = np.where(dataframe[column_name] < 0, 0, dataframe[column_name])

# Example usage:
# Create a sample DataFrame
data = {'A': [-1, 2, -3, 4, -5],
        'B': [5, -6, 7, -8, 9]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Replace negative values in column 'A' with zeros
replace_negative_with_zeros(df, 'A')

print("\nDataFrame after replacing negative values in column 'A' with zeros:")
print(df)


Original DataFrame:
   A  B
0 -1  5
1  2 -6
2 -3  7
3  4 -8
4 -5  9

DataFrame after replacing negative values in column 'A' with zeros:
   A  B
0  0  5
1  2 -6
2  0  7
3  4 -8
4  0  9


In [30]:
#26. Access the 3rd element from the given NumPy array.

In [31]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Accessing the 3rd element (index 2)
third_element = arr[2]

print("The 3rd element:", third_element)


The 3rd element: 30


In [32]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array.

In [33]:
# Create a 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Retrieve the element at index (1, 2)
element_at_1_2 = arr_2d[1, 2]

print("Element at index (1, 2):", element_at_1_2)


Element at index (1, 2): 6


In [34]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array

In [35]:
arr = np.array([3, 8, 2, 10, 5, 7])

# Boolean indexing to extract elements greater than 5
result = arr[arr > 5]

print("Elements greater than 5:", result)


Elements greater than 5: [ 8 10  7]


In [36]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Perform basic slicing to extract elements from index 2 to 5 (inclusive)
result = arr[2:6]

print("Elements from index 2 to 5 (inclusive):", result)


Elements from index 2 to 5 (inclusive): [3 4 5 6]


In [38]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array

In [39]:
# Create a 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Slice the 2D array to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]

print("Sub-array [[2, 3], [5, 6]]:")
print(sub_array)


Sub-array [[2, 3], [5, 6]]:
[[2 3]
 [5 6]]


In [40]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array

In [41]:
def extract_elements_2d_array(arr_2d, indices):
    # Flatten the 2D array and use advanced indexing with the provided indices
    return arr_2d.flatten()[indices]

# Example usage:
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

indices = np.array([1, 4, 6, 7])  # Indices to extract elements from the 2D array

result = extract_elements_2d_array(arr_2d, indices)
print("Extracted elements based on provided indices:", result)


Extracted elements based on provided indices: [2 5 7 8]


In [42]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.


In [43]:
def filter_greater_than_threshold(arr, threshold):
    return arr[arr > threshold]

# Example usage:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
threshold = 5

result = filter_greater_than_threshold(arr, threshold)
print("Filtered elements greater than", threshold, ":", result)


Filtered elements greater than 5 : [6 7 8 9]


In [44]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension

In [45]:
def extract_elements_3d_array(arr_3d, indices_dim1, indices_dim2, indices_dim3):
    # Use advanced indexing with provided indices for each dimension
    return arr_3d[indices_dim1, indices_dim2, indices_dim3]

# Example usage:
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]]])

indices_dim1 = np.array([0, 1])  # Indices for dimension 1
indices_dim2 = np.array([1, 2])  # Indices for dimension 2
indices_dim3 = np.array([0, 2])  # Indices for dimension 3

result = extract_elements_3d_array(arr_3d, indices_dim1, indices_dim2, indices_dim3)
print("Extracted elements from the 3D array based on provided indices:")
print(result)


Extracted elements from the 3D array based on provided indices:
[ 4 18]


In [46]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing

In [47]:
def filter_with_multiple_conditions(arr, condition1, condition2):
    return arr[(condition1) & (condition2)]

# Example usage:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Define conditions
condition1 = arr > 3
condition2 = arr % 2 == 0

# Apply boolean indexing with multiple conditions
result = filter_with_multiple_conditions(arr, condition1, condition2)
print("Elements from the array satisfying both conditions:", result)



Elements from the array satisfying both conditions: [4 6 8]


In [1]:
#35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [2]:
import numpy as np

def extract_elements(array, row_indices, col_indices):
  
    # Ensure row_indices and col_indices are numpy arrays
    row_indices = np.array(row_indices)
    col_indices = np.array(col_indices)
    
    # Use advanced indexing to extract elements
    extracted_elements = array[row_indices, col_indices]
    
    return extracted_elements

# Example usage:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

row_indices = [0, 1, 2]
col_indices = [2, 1, 0]

elements = extract_elements(array, row_indices, col_indices)
print(elements)  # Output: [3 5 7]


[3 5 7]


In [3]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [4]:
import numpy as np

# Create a 3x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add a scalar value of 5 to each element using broadcasting
arr_plus_5 = arr + 5

print(arr_plus_5)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [5]:
#37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [6]:
import numpy as np

# Define the arrays
arr1 = np.array([[2, 3, 4]])  # Shape (1, 3)
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])  # Shape (3, 4)

# Use broadcasting to multiply each row of arr2 by the corresponding element in arr1
# First, we need to reshape arr1 to be (3, 1) so that it can be broadcast across arr2
arr1_reshaped = arr1.reshape(3, 1)
result = arr2 * arr1_reshaped

print(result)


[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [7]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [8]:
import numpy as np

# Define the arrays
arr1 = np.array([1, 2, 3, 4])  # Shape (4,)
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])  # Shape (4, 3)

# Add arr1 to each row of arr2 using broadcasting
result = arr2 + arr1[:, np.newaxis]

print(result)


[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [9]:
#39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting

In [10]:
import numpy as np

# Define the arrays
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([[4, 5, 6]])      # Shape (1, 3)

# Add the arrays using broadcasting
result = arr1 + arr2

print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [11]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility

In [12]:
import numpy as np

# Define the arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  # Shape (2, 3)

arr2 = np.array([[7, 8],
                 [9, 10]])    # Shape (2, 2)

arr2_expanded = np.tile(arr2, (1, 2))[:, :3]

# Perform element-wise multiplication using broadcasting
result = arr1 * arr2_expanded

print(result)


[[ 7 16 21]
 [36 50 54]]


In [13]:
#41. Calculate column wise mean for the given array

In [14]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Calculate the column-wise mean
column_wise_mean = np.mean(arr, axis=0)

print(column_wise_mean)


[4. 5. 6.]


In [15]:
#42. Find maximum value in each row of the given array

In [16]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find the maximum value in each row
row_wise_max = np.max(arr, axis=1)

print(row_wise_max)


[3 6]


In [17]:
#43. For the given array, find indices of maximum value in each column.


In [18]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find the indices of the maximum values in each column
column_wise_max_indices = np.argmax(arr, axis=0)

print(column_wise_max_indices)


[1 1 1]


In [19]:
#44. For the given array, apply custom function to calculate moving sum along rows.

In [20]:
import numpy as np

def moving_sum_along_rows(arr, window_size):
    padded_arr = np.pad(arr, ((0, 0), (window_size - 1, 0)), mode='constant')
    # Use a convolution operation to calculate the moving sum along rows
    moving_sum = np.apply_along_axis(lambda row: np.convolve(row, np.ones(window_size), mode='valid'), axis=1, arr=padded_arr)
    return moving_sum

# Given array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Window size for moving sum
window_size = 2

# Calculate moving sum along rows
result = moving_sum_along_rows(arr, window_size)
print("Moving sum along rows:")
print(result)


Moving sum along rows:
[[ 1.  3.  5.]
 [ 4.  9. 11.]]


In [21]:
#45. In the given array, check if all elements in each column are even

In [22]:
import numpy as np

# Given array
arr = np.array([[2, 4, 6], [3, 5, 7]])

# Check if all elements in each column are even
all_even_columns = np.all(arr % 2 == 0, axis=0)

print("Are all elements in each column even?")
print(all_even_columns)


Are all elements in each column even?
[False False False]


In [23]:
#46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix

In [24]:
import numpy as np

# Given array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Specify the dimensions of the desired matrix
m = 2  # Number of rows
n = 3  # Number of columns

# Reshape the array into a matrix of dimensions m x n
reshaped_matrix = original_array.reshape(m, n)

print("Reshaped matrix:")
print(reshaped_matrix)


Reshaped matrix:
[[1 2 3]
 [4 5 6]]


In [25]:
#47. Create a function that takes a matrix as input and returns the flattened array.

In [26]:
import numpy as np

def flatten_matrix(input_matrix):
    # Flatten the matrix into a 1D array
    flattened_array = input_matrix.flatten()
    return flattened_array

# Given matrix
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Call the function to flatten the matrix
flattened_array = flatten_matrix(input_matrix)

print("Flattened array:")
print(flattened_array)


Flattened array:
[1 2 3 4 5 6]


In [27]:
#48. Write a function that concatenates two given arrays along a specified axis.

In [28]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    # Concatenate the arrays along the specified axis
    concatenated_array = np.concatenate((arr1, arr2), axis=axis)
    return concatenated_array

# Given arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Call the function to concatenate arrays along axis 0 (rows)
result_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:")
print(result_axis0)

# Call the function to concatenate arrays along axis 1 (columns)
result_axis1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:")
print(result_axis1)


Concatenated along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [29]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis.

In [30]:
import numpy as np

def split_array(original_array, num_splits, axis=0):
    # Split the array into multiple sub-arrays along the specified axis
    sub_arrays = np.split(original_array, num_splits, axis=axis)
    return sub_arrays

# Given array
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Call the function to split the array into 3 sub-arrays along axis 0 (rows)
result = split_array(original_array, num_splits=3, axis=0)
print("Sub-arrays after splitting along axis 0:")
for sub_array in result:
    print(sub_array)

# Call the function to split the array into 3 sub-arrays along axis 1 (columns)
result = split_array(original_array, num_splits=3, axis=1)
print("Sub-arrays after splitting along axis 1:")
for sub_array in result:
    print(sub_array)


Sub-arrays after splitting along axis 0:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]
Sub-arrays after splitting along axis 1:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [31]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.

In [32]:
import numpy as np

def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements at specified indices
    for index, value in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, index, value)
    
    # Delete elements at specified indices
    original_array = np.delete(original_array, indices_to_delete)
    
    return original_array

# Given array and indices
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

# Call the function to insert and delete elements
result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Array after insertion and deletion:")
print(result_array)


Array after insertion and deletion:
[ 1 10 11  4  5]


In [33]:
#51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`

In [35]:
import numpy as np

# Create arr1 with random integers
arr1 = np.random.randint(1, 100, size=(5, 5))  # Random integers between 1 and 100 in a 5x5 array
print("arr1:")
print(arr1)

# Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)  # Integers from 1 to 10
print("\narr2:")
print(arr2)

# Perform element-wise addition between arr1 and arr2
result = (arr1 + arr2)
print("\nElement-wise addition:")
print(result)


arr1:
[[53 54 83 67 96]
 [57 31 77 98 96]
 [35 41 59 31 25]
 [17  4 30 70 50]
 [49 85 28  9 40]]

arr2:
[ 1  2  3  4  5  6  7  8  9 10]


ValueError: operands could not be broadcast together with shapes (5,5) (10,) 

In [36]:
##52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [37]:
import numpy as np

# Generate arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)
print("arr1:")
print(arr1)

# Generate arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)
print("\narr2:")
print(arr2)

# Subtract arr2 from arr1 element-wise
result = arr1 - arr2
print("\nElement-wise subtraction:")
print(result)


arr1:
[10  9  8  7  6  5  4  3  2  1]

arr2:
[ 1  2  3  4  5  6  7  8  9 10]

Element-wise subtraction:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [38]:
#53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

In [39]:
import numpy as np

# Create arr1 with random integers
arr1 = np.random.randint(1, 100, size=(3, 3))  # Random integers between 1 and 100 in a 3x3 array
print("arr1:")
print(arr1)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)  # Integers from 1 to 5
print("\narr2:")
print(arr2)

# Perform element-wise multiplication between arr1 and arr2
result = arr1 * arr2
print("\nElement-wise multiplication:")
print(result)


arr1:
[[74 20 88]
 [46 97 28]
 [49 99 23]]

arr2:
[1 2 3 4 5]


ValueError: operands could not be broadcast together with shapes (3,3) (5,) 

In [41]:
#54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [42]:
import numpy as np

# Generate arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)
print("arr1:")
print(arr1)

# Generate arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)
print("\narr2:")
print(arr2)

# Perform element-wise division between arr1 and arr2
result = arr1 / arr2
print("\nElement-wise division:")
print(result)


arr1:
[ 2  4  6  8 10]

arr2:
[1 2 3 4 5]

Element-wise division:
[2. 2. 2. 2. 2.]


In [43]:
#55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [44]:
import numpy as np

# Create arr1 with integers from 1 to 5
arr1 = np.arange(1, 6)
print("arr1:")
print(arr1)

# Create arr2 with the same numbers reversed
arr2 = np.flip(arr1)
print("\narr2:")
print(arr2)

# Calculate the exponentiation of arr1 raised to the power of arr2 element-wise
result = np.power(arr1, arr2)
print("\nExponentiation of arr1 raised to the power of arr2 element-wise:")
print(result)


arr1:
[1 2 3 4 5]

arr2:
[5 4 3 2 1]

Exponentiation of arr1 raised to the power of arr2 element-wise:
[ 1 16 27 16  5]


In [45]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

In [46]:
import numpy as np

def count_substring_occurrences(arr, substring):
    # Initialize count variable to store the total occurrences
    count = 0
    
    # Iterate over each element in the array
    for string in arr:
        # Count occurrences of substring in the current string
        count += string.count(substring)
    
    return count

# Given array of strings
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

# Substring to count occurrences
substring = 'hello'

# Call the function to count occurrences of the substring
occurrences = count_substring_occurrences(arr, substring)
print("Occurrences of '{}' within the array: {}".format(substring, occurrences))


Occurrences of 'hello' within the array: 3


In [47]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings.

#arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [48]:
import numpy as np

def extract_uppercase_characters(arr):
    # Initialize an empty list to store uppercase characters
    uppercase_characters = []

    # Iterate over each element in the array
    for string in arr:
        # Extract uppercase characters from the current string
        uppercase_characters.extend(char for char in string if char.isupper())

    return uppercase_characters

# Given array of strings
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Call the function to extract uppercase characters
result = extract_uppercase_characters(arr)
print("Uppercase characters extracted from the array:")
print(result)


Uppercase characters extracted from the array:
['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


In [49]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

In [50]:
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    # Create a new array to store the modified strings
    modified_arr = np.empty_like(arr)

    # Iterate over each element in the array
    for i, string in enumerate(arr):
        # Replace occurrences of old_substring with new_substring
        modified_arr[i] = string.replace(old_substring, new_substring)

    return modified_arr

# Given array of strings
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Substring to replace and new substring
old_substring = 'ap'
new_substring = 'orange'

# Call the function to replace occurrences of the substring
result = replace_substring(arr, old_substring, new_substring)
print("Array after replacing '{}' with '{}':".format(old_substring, new_substring))
print(result)


Array after replacing 'ap' with 'orange':
['orangeple' 'banana' 'grorangee' 'pineorang']


In [51]:
#59. Write a function that concatenates strings in a NumPy array element-wise.

In [52]:
import numpy as np

def concatenate_strings(arr1, arr2):
    # Ensure both arrays have the same shape
    if arr1.shape != arr2.shape:
        raise ValueError("Arrays must have the same shape for element-wise concatenation.")

    # Create a new array to store the concatenated strings
    concatenated_arr = np.empty_like(arr1, dtype=np.object)

    # Iterate over each element in the arrays
    for i in range(len(arr1)):
        # Concatenate corresponding strings from arr1 and arr2
        concatenated_arr[i] = arr1[i] + arr2[i]

    return concatenated_arr

# Given arrays of strings
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Call the function to concatenate strings element-wise
result = concatenate_strings(arr1, arr2)
print("Element-wise concatenation:")
print(result)


Element-wise concatenation:
['HelloOpen' 'WorldAI']


/tmp/ipykernel_77/1366495304.py:9: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  concatenated_arr = np.empty_like(arr1, dtype=np.object)


In [53]:
#60. Write a function that finds the length of the longest string in a NumPy array.

#arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [54]:
import numpy as np

def longest_string_length(arr):
    # Initialize the maximum length variable
    max_length = 0

    # Iterate over each element in the array
    for string in arr:
        # Update the maximum length if the length of the current string is greater
        max_length = max(max_length, len(string))

    return max_length

# Given array of strings
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Call the function to find the length of the longest string
result = longest_string_length(arr)
print("Length of the longest string in the array:", result)



Length of the longest string in the array: 9


In [55]:
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [56]:
import numpy as np

# Create a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Compute the mean of the dataset
mean = np.mean(dataset)

# Compute the median of the dataset
median = np.median(dataset)

# Compute the variance of the dataset
variance = np.var(dataset)

# Compute the standard deviation of the dataset
std_deviation = np.std(dataset)

# Print the computed statistics
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)


Mean: 495.24
Median: 492.0
Variance: 81886.6424
Standard Deviation: 286.1584218575438


In [57]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [58]:
import numpy as np

# Generate an array of 50 random numbers between 1 and 100
dataset = np.random.randint(1, 101, size=50)

# Find the 25th and 75th percentiles of the dataset
percentile_25th = np.percentile(dataset, 25)
percentile_75th = np.percentile(dataset, 75)

# Print the percentiles
print("25th Percentile:", percentile_25th)
print("75th Percentile:", percentile_75th)


25th Percentile: 37.0
75th Percentile: 75.75


In [59]:
#63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [60]:
import numpy as np

# Create two arrays representing two sets of variables
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# Compute the correlation coefficient between the arrays
correlation_coefficient = np.corrcoef(array1, array2)[0, 1]

# Print the correlation coefficient
print("Correlation Coefficient between array1 and array2:", correlation_coefficient)


Correlation Coefficient between array1 and array2: -0.9999999999999999


In [61]:
#64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [62]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8], [9, 10], [11, 12]])

# Perform matrix multiplication
result_matrix = np.dot(matrix1, matrix2)

# Print the result
print("Result of matrix multiplication:")
print(result_matrix)


Result of matrix multiplication:
[[ 58  64]
 [139 154]]


In [63]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [64]:
import numpy as np

# Create an array of 50 integers between 10 and 1000
data = np.random.randint(10, 1001, 50)

# Calculate percentiles and quartiles
percentiles = np.percentile(data, [10, 50, 90])
first_quartile = np.percentile(data, 25)
third_quartile = np.percentile(data, 75)

print("Data:", data)
print("10th percentile:", percentiles[0])
print("50th percentile (median):", percentiles[1])
print("90th percentile:", percentiles[2])
print("First quartile:", first_quartile)
print("Third quartile:", third_quartile)


Data: [929 442 613 856 557 305  78 760  67 808 884  44 434 873 974 151  18 853
 441 306 267 912 754 444 297 415 465 621 658 163 597 137  12 192  33  88
 559 249 866 719 705 547  78 859 584 879  27 806 642 398]
10th percentile: 64.7
50th percentile (median): 506.0
90th percentile: 873.6
First quartile: 206.25
Third quartile: 758.5


In [65]:
#66. Create a NumPy array of integers and find the index of a specific element.

In [66]:
import numpy as np

# Create a NumPy array of integers
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Define the element to find
element_to_find = 50

# Find the index of the element
index = np.where(array == element_to_find)[0]

if index.size > 0:
    print("Index of", element_to_find, ":", index[0])
else:
    print(element_to_find, "not found in the array.")


Index of 50 : 4


In [67]:
#67. Generate a random NumPy array and sort it in ascending order

In [68]:
import numpy as np

# Generate a random NumPy array
random_array = np.random.randint(0, 100, size=10)

# Sort the array in ascending order
sorted_array = np.sort(random_array)

print("Original array:", random_array)
print("Sorted array in ascending order:", sorted_array)


Original array: [ 8 93 16 65 97 98 40 30 16 51]
Sorted array in ascending order: [ 8 16 16 30 40 51 65 93 97 98]


In [69]:
#68. Filter elements >20  in the given NumPy array.

In [70]:
import numpy as np

# Given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_array = arr[arr > 20]

print("Original array:", arr)
print("Filtered elements greater than 20:", filtered_array)


Original array: [12 25  6 42  8 30]
Filtered elements greater than 20: [25 42 30]


In [71]:
#69. Filter elements which are divisible by 3 from a given NumPy array.

In [72]:
import numpy as np

# Given NumPy array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_array = arr[arr % 3 == 0]

print("Original array:", arr)
print("Filtered elements divisible by 3:", filtered_array)


Original array: [ 1  5  8 12 15]
Filtered elements divisible by 3: [12 15]


In [73]:
#70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

In [74]:
import numpy as np

# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements within the range [20, 40]
filtered_array = arr[(arr >= 20) & (arr <= 40)]

print("Original array:", arr)
print("Filtered elements between 20 and 40 (inclusive):", filtered_array)


Original array: [10 20 30 40 50]
Filtered elements between 20 and 40 (inclusive): [20 30 40]


In [75]:
#71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

In [76]:
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3])

# Check byte order
byte_order = arr.dtype.byteorder

print("Byte order of the array:", byte_order)


Byte order of the array: =


In [77]:
#72. For the given NumPy array, perform byte swapping in place using `byteswap(

In [78]:
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(True)

print("Byte-swapped array:", arr)


Byte-swapped array: [16777216 33554432 50331648]


In [79]:
#73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.

In [80]:
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Swap byte order without modifying the original array
swapped_arr = arr.newbyteorder()

print("Original array:", arr)
print("Array with swapped byte order:", swapped_arr)


Original array: [1 2 3]
Array with swapped byte order: [16777216 33554432 50331648]


In [81]:
#74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.

In [82]:
import numpy as np
import sys

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Check system endianness and swap byte order accordingly
if sys.byteorder != arr.dtype.byteorder:
    swapped_arr = arr.newbyteorder()
else:
    swapped_arr = arr

print("Original array:", arr)
print("Array with swapped byte order if necessary:", swapped_arr)


Original array: [1 2 3]
Array with swapped byte order if necessary: [16777216 33554432 50331648]


In [83]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.

In [84]:
import numpy as np
import sys

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Check if byte swapping is necessary
if arr.dtype.byteorder != sys.byteorder:
    print("Byte swapping is necessary for the current system.")
else:
    print("Byte swapping is not necessary for the current system.")


Byte swapping is necessary for the current system.


In [85]:
#76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`

In [86]:
import numpy as np

# Create arr1 with values from 1 to 10
arr1 = np.arange(1, 11)

# Create a copy of arr1 named copy_arr
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 100

# Check if modifying copy_arr affects arr1
print("Original arr1:", arr1)
print("Modified copy_arr:", copy_arr)


Original arr1: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy_arr: [100   2   3   4   5   6   7   8   9  10]


In [87]:
#77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [88]:
import numpy as np

# Create a 2D NumPy array (matrix) of shape (3, 3) with random integers
matrix = np.random.randint(1, 100, size=(3, 3))

# Extract a slice (view_slice) from the matrix
view_slice = matrix[:2, :2]  # Extracting the top-left 2x2 slice

# Modify an element in view_slice
view_slice[0, 0] = 999

# Print both the original matrix and the modified slice
print("Original matrix:")
print(matrix)

print("\nModified slice (view_slice):")
print(view_slice)


Original matrix:
[[999   7  44]
 [  2  87  66]
 [ 29  83  24]]

Modified slice (view_slice):
[[999   7]
 [  2  87]]


In [89]:
##78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [90]:
import numpy as np

# Create a NumPy array of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

# Extract a slice (view_b) from array_a
view_b = array_a[:2, :2]  # Extracting the top-left 2x2 slice

# Broadcast the addition of 5 to view_b
view_b += 5

# Print both the original array_a and the modified slice view_b
print("Original array_a:")
print(array_a)

print("\nModified slice (view_b):")
print(view_b)


Original array_a:
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]

Modified slice (view_b):
[[ 6  7]
 [ 9 10]]


In [91]:
#79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in`reshaped_view` and check if it reflects changes in the original `orig_array`.

In [92]:
import numpy as np

# Create a NumPy array of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Create a reshaped view of shape (4, 2) from orig_array
reshaped_view = orig_array.T.reshape(4, 2)

# Modify an element in reshaped_view
reshaped_view[0, 0] = 999

# Print both the original orig_array and the modified reshaped_view
print("Original orig_array:")
print(orig_array)

print("\nModified reshaped_view:")
print(reshaped_view)


Original orig_array:
[[999   2   3   4]
 [  5   6   7   8]]

Modified reshaped_view:
[[999   5]
 [  2   6]
 [  3   7]
 [  4   8]]


In [93]:
#80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` ofelements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [96]:
import numpy as np

# Create a NumPy array of shape (3, 4) with random integers
data = np.random.randint(1, 10, size=(3, 4))

# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Modify an element in data_copy
data_copy[0] = 999

# Print both the original data and the modified data_copy
print("Original data:")
print(data)

print("\nModified data_copy:")
print(data_copy)


Original data:
[[7 1 7 7]
 [9 2 4 9]
 [9 2 6 5]]

Modified data_copy:
[999   7   7   9   9   9   6]


In [97]:
#81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them

In [98]:
import numpy as np

# Create matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

# Addition operation
addition_result = A + B

# Subtraction operation
subtraction_result = A - B

# Print the results
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition result (A + B):")
print(addition_result)

print("\nSubtraction result (A - B):")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8  9]
 [10 11 12]]

Addition result (A + B):
[[ 8 10 12]
 [14 16 18]]

Subtraction result (A - B):
[[-6 -6 -6]
 [-6 -6 -6]]


In [99]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [100]:
import numpy as np

# Generate matrices C (3x2) and D (2x4)
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])

# Perform matrix multiplication
multiplication_result = np.dot(C, D)

# Print the result
print("Matrix C:")
print(C)

print("\nMatrix D:")
print(D)

print("\nMatrix multiplication result (C * D):")
print(multiplication_result)


Matrix C:
[[1 2]
 [3 4]
 [5 6]]

Matrix D:
[[ 7  8  9 10]
 [11 12 13 14]]

Matrix multiplication result (C * D):
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [101]:
#83. Create a matrix `E` and find its transpose

In [102]:
import numpy as np

# Create a matrix E
E = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Find the transpose of matrix E
E_transpose = np.transpose(E)

# Print the original matrix and its transpose
print("Matrix E:")
print(E)

print("\nTranspose of matrix E:")
print(E_transpose)


Matrix E:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of matrix E:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
